<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 10 Predicting more things | R @ R(D)SVS</title>
  <meta name="description" content="This book will help you get started in R. It’s designed for students (and staff) at R(D)SVS, and is free to use and adapt." />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 10 Predicting more things | R @ R(D)SVS" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This book will help you get started in R. It’s designed for students (and staff) at R(D)SVS, and is free to use and adapt." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 10 Predicting more things | R @ R(D)SVS" />
  
  <meta name="twitter:description" content="This book will help you get started in R. It’s designed for students (and staff) at R(D)SVS, and is free to use and adapt." />
  

<meta name="author" content="Jill R D MacKay" />


<meta name="date" content="2021-01-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="statsbasic.html"/>
<link rel="next" href="choosestats.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="css\styles.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>R @ R(D)SVS</a></li>
<li class="chapter" data-level="" data-path="about.html"><a href="about.html"><i class="fa fa-check"></i>About this book</a><ul>
<li class="chapter" data-level="0.1" data-path="about.html"><a href="about.html#howuse"><i class="fa fa-check"></i><b>0.1</b> How to use this book</a><ul>
<li class="chapter" data-level="0.1.1" data-path="about.html"><a href="about.html#useinclass"><i class="fa fa-check"></i><b>0.1.1</b> As a student in class</a></li>
<li class="chapter" data-level="0.1.2" data-path="about.html"><a href="about.html#useindependent"><i class="fa fa-check"></i><b>0.1.2</b> As a student learning independently</a></li>
<li class="chapter" data-level="0.1.3" data-path="about.html"><a href="about.html#useteach"><i class="fa fa-check"></i><b>0.1.3</b> As a teacher</a></li>
</ul></li>
<li class="chapter" data-level="0.2" data-path="about.html"><a href="about.html#usetips"><i class="fa fa-check"></i><b>0.2</b> Tips for using an online textbook</a></li>
<li class="chapter" data-level="0.3" data-path="about.html"><a href="about.html#license"><i class="fa fa-check"></i><b>0.3</b> Licensing</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="install.html"><a href="install.html"><i class="fa fa-check"></i><b>1</b> Installing R</a><ul>
<li class="chapter" data-level="1.1" data-path="install.html"><a href="install.html#install_r"><i class="fa fa-check"></i><b>1.1</b> Install R</a></li>
<li class="chapter" data-level="1.2" data-path="install.html"><a href="install.html#install_rs"><i class="fa fa-check"></i><b>1.2</b> Install R Studio</a><ul>
<li class="chapter" data-level="1.2.1" data-path="install.html"><a href="install.html#navigate_rs"><i class="fa fa-check"></i><b>1.2.1</b> Quick R Studio Navigation Guide</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="install.html"><a href="install.html#install_rsc"><i class="fa fa-check"></i><b>1.3</b> Using the Cloud</a></li>
<li class="chapter" data-level="1.4" data-path="install.html"><a href="install.html#install_vids"><i class="fa fa-check"></i><b>1.4</b> Install R and R Studio - Video Instruction</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="start.html"><a href="start.html"><i class="fa fa-check"></i><b>2</b> Getting Started</a><ul>
<li class="chapter" data-level="2.1" data-path="start.html"><a href="start.html#thesecret"><i class="fa fa-check"></i><b>2.1</b> The Big Secret</a><ul>
<li class="chapter" data-level="2.1.1" data-path="start.html"><a href="start.html#ex_tidytuesday"><i class="fa fa-check"></i><b>2.1.1</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="start.html"><a href="start.html#projects"><i class="fa fa-check"></i><b>2.2</b> Projects</a></li>
<li class="chapter" data-level="2.3" data-path="start.html"><a href="start.html#environment"><i class="fa fa-check"></i><b>2.3</b> Environment</a><ul>
<li class="chapter" data-level="2.3.1" data-path="start.html"><a href="start.html#ex_env"><i class="fa fa-check"></i><b>2.3.1</b> Exercise - Environment</a></li>
<li class="chapter" data-level="2.3.2" data-path="start.html"><a href="start.html#ex_func"><i class="fa fa-check"></i><b>2.3.2</b> Exercise - Functions</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="start.html"><a href="start.html#packages"><i class="fa fa-check"></i><b>2.4</b> Packages</a><ul>
<li class="chapter" data-level="2.4.1" data-path="start.html"><a href="start.html#ex_packages"><i class="fa fa-check"></i><b>2.4.1</b> Exercise - Install and Load a Package</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="start.html"><a href="start.html#scripts_rmd"><i class="fa fa-check"></i><b>2.5</b> R Markdown vs R Scripts</a><ul>
<li class="chapter" data-level="2.5.1" data-path="start.html"><a href="start.html#r-scripts"><i class="fa fa-check"></i><b>2.5.1</b> R Scripts</a></li>
<li class="chapter" data-level="2.5.2" data-path="start.html"><a href="start.html#r-markdown"><i class="fa fa-check"></i><b>2.5.2</b> R Markdown</a></li>
<li class="chapter" data-level="2.5.3" data-path="start.html"><a href="start.html#video_rmd"><i class="fa fa-check"></i><b>2.5.3</b> A video on R Markdown</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="start.html"><a href="start.html#video_env"><i class="fa fa-check"></i><b>2.6</b> Video Introductions</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>3</b> Data</a><ul>
<li class="chapter" data-level="3.1" data-path="data.html"><a href="data.html#packages-for-this-chapter"><i class="fa fa-check"></i><b>3.1</b> Packages for this chapter</a></li>
<li class="chapter" data-level="3.2" data-path="data.html"><a href="data.html#data_builtin"><i class="fa fa-check"></i><b>3.2</b> Built In Data</a></li>
<li class="chapter" data-level="3.3" data-path="data.html"><a href="data.html#ex_inbuiltdata"><i class="fa fa-check"></i><b>3.3</b> Exercise</a></li>
<li class="chapter" data-level="3.4" data-path="data.html"><a href="data.html#created_data"><i class="fa fa-check"></i><b>3.4</b> Data you create</a></li>
<li class="chapter" data-level="3.5" data-path="data.html"><a href="data.html#ex_createdata"><i class="fa fa-check"></i><b>3.5</b> Exercise - Creating data</a></li>
<li class="chapter" data-level="3.6" data-path="data.html"><a href="data.html#data_load"><i class="fa fa-check"></i><b>3.6</b> Loading data from your hard drive</a></li>
<li class="chapter" data-level="3.7" data-path="data.html"><a href="data.html#ex_data_load"><i class="fa fa-check"></i><b>3.7</b> Loading data</a><ul>
<li class="chapter" data-level="3.7.1" data-path="data.html"><a href="data.html#loading-from-a-csv"><i class="fa fa-check"></i><b>3.7.1</b> Loading from a CSV</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="data.html"><a href="data.html#ex_loadcsv"><i class="fa fa-check"></i><b>3.8</b> Exercise</a><ul>
<li class="chapter" data-level="3.8.1" data-path="data.html"><a href="data.html#loading-from-an-excel-file"><i class="fa fa-check"></i><b>3.8.1</b> Loading from an Excel file</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="data.html"><a href="data.html#ex_loadexcel"><i class="fa fa-check"></i><b>3.9</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="charts.html"><a href="charts.html"><i class="fa fa-check"></i><b>4</b> Charts</a><ul>
<li class="chapter" data-level="4.1" data-path="charts.html"><a href="charts.html#datavis"><i class="fa fa-check"></i><b>4.1</b> Data Visualisation</a><ul>
<li class="chapter" data-level="4.1.1" data-path="charts.html"><a href="charts.html#vis_bad"><i class="fa fa-check"></i><b>4.1.1</b> When charts go bad</a></li>
<li class="chapter" data-level="4.1.2" data-path="charts.html"><a href="charts.html#vis_anatomy"><i class="fa fa-check"></i><b>4.1.2</b> Chart anatomy</a></li>
<li class="chapter" data-level="4.1.3" data-path="charts.html"><a href="charts.html#vis_bar"><i class="fa fa-check"></i><b>4.1.3</b> Bar charts</a></li>
<li class="chapter" data-level="4.1.4" data-path="charts.html"><a href="charts.html#vis_hist"><i class="fa fa-check"></i><b>4.1.4</b> Histograms</a></li>
<li class="chapter" data-level="4.1.5" data-path="charts.html"><a href="charts.html#vis_scatter"><i class="fa fa-check"></i><b>4.1.5</b> Scatterplots</a></li>
<li class="chapter" data-level="4.1.6" data-path="charts.html"><a href="charts.html#vis_box"><i class="fa fa-check"></i><b>4.1.6</b> Boxplots</a></li>
<li class="chapter" data-level="4.1.7" data-path="charts.html"><a href="charts.html#vis_infographic"><i class="fa fa-check"></i><b>4.1.7</b> Infographics</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="ggplot.html"><a href="ggplot.html"><i class="fa fa-check"></i><b>5</b> ggplot2</a><ul>
<li class="chapter" data-level="5.1" data-path="ggplot.html"><a href="ggplot.html#why-ggplot"><i class="fa fa-check"></i><b>5.1</b> Why ggplot?</a></li>
<li class="chapter" data-level="5.2" data-path="ggplot.html"><a href="ggplot.html#gg_build"><i class="fa fa-check"></i><b>5.2</b> Building a ggplot object (a scatterplot)</a><ul>
<li class="chapter" data-level="5.2.1" data-path="ggplot.html"><a href="ggplot.html#gg_axis"><i class="fa fa-check"></i><b>5.2.1</b> Changing an axis in ggplot2</a></li>
<li class="chapter" data-level="5.2.2" data-path="ggplot.html"><a href="ggplot.html#gg_theme"><i class="fa fa-check"></i><b>5.2.2</b> Changing themes</a></li>
<li class="chapter" data-level="5.2.3" data-path="ggplot.html"><a href="ggplot.html#gg_labs"><i class="fa fa-check"></i><b>5.2.3</b> Changing labels and titles</a></li>
<li class="chapter" data-level="5.2.4" data-path="ggplot.html"><a href="ggplot.html#gg_smooth"><i class="fa fa-check"></i><b>5.2.4</b> Adding regression lines to ggplot</a></li>
<li class="chapter" data-level="5.2.5" data-path="ggplot.html"><a href="ggplot.html#gg_groups"><i class="fa fa-check"></i><b>5.2.5</b> Adding groups to ggplot</a></li>
<li class="chapter" data-level="5.2.6" data-path="ggplot.html"><a href="ggplot.html#gg_legend"><i class="fa fa-check"></i><b>5.2.6</b> Changing legends</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="ggplot.html"><a href="ggplot.html#gg_boxplot"><i class="fa fa-check"></i><b>5.3</b> Building a boxplot</a></li>
<li class="chapter" data-level="5.4" data-path="ggplot.html"><a href="ggplot.html#gg_facets"><i class="fa fa-check"></i><b>5.4</b> Facets</a></li>
<li class="chapter" data-level="5.5" data-path="ggplot.html"><a href="ggplot.html#gg_bars"><i class="fa fa-check"></i><b>5.5</b> Bar charts</a></li>
<li class="chapter" data-level="5.6" data-path="ggplot.html"><a href="ggplot.html#ex_ggplot"><i class="fa fa-check"></i><b>5.6</b> Exercise</a></li>
<li class="chapter" data-level="5.7" data-path="ggplot.html"><a href="ggplot.html#gg_vids"><i class="fa fa-check"></i><b>5.7</b> Videos</a></li>
<li class="chapter" data-level="5.8" data-path="ggplot.html"><a href="ggplot.html#gg_resources"><i class="fa fa-check"></i><b>5.8</b> Useful resources</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="dataprocessing.html"><a href="dataprocessing.html"><i class="fa fa-check"></i><b>6</b> Data Processing</a><ul>
<li class="chapter" data-level="6.1" data-path="dataprocessing.html"><a href="dataprocessing.html#workflows"><i class="fa fa-check"></i><b>6.1</b> Workflows</a><ul>
<li class="chapter" data-level="6.1.1" data-path="dataprocessing.html"><a href="dataprocessing.html#an-example-of-sharing-code"><i class="fa fa-check"></i><b>6.1.1</b> An example of sharing code</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="dataprocessing.html"><a href="dataprocessing.html#openrmd"><i class="fa fa-check"></i><b>6.2</b> Opening R Markdown Docs</a></li>
<li class="chapter" data-level="6.3" data-path="dataprocessing.html"><a href="dataprocessing.html#codermd"><i class="fa fa-check"></i><b>6.3</b> Running Code</a></li>
<li class="chapter" data-level="6.4" data-path="dataprocessing.html"><a href="dataprocessing.html#editrmd"><i class="fa fa-check"></i><b>6.4</b> Editing R Markdown Docs</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="tidyverse.html"><a href="tidyverse.html"><i class="fa fa-check"></i><b>7</b> The Tidyverse</a><ul>
<li class="chapter" data-level="7.1" data-path="tidyverse.html"><a href="tidyverse.html#tidy_opinions"><i class="fa fa-check"></i><b>7.1</b> Opinionated Packages</a></li>
<li class="chapter" data-level="7.2" data-path="tidyverse.html"><a href="tidyverse.html#data-for-this-chapter"><i class="fa fa-check"></i><b>7.2</b> Data for this chapter</a></li>
<li class="chapter" data-level="7.3" data-path="tidyverse.html"><a href="tidyverse.html#mutate"><i class="fa fa-check"></i><b>7.3</b> Mutating data</a><ul>
<li class="chapter" data-level="7.3.1" data-path="tidyverse.html"><a href="tidyverse.html#mutate-to-change-a-variable-type."><i class="fa fa-check"></i><b>7.3.1</b> Mutate to change a variable type.</a></li>
<li class="chapter" data-level="7.3.2" data-path="tidyverse.html"><a href="tidyverse.html#mutate-to-change-the-contents-of-data"><i class="fa fa-check"></i><b>7.3.2</b> Mutate to change the contents of data</a></li>
<li class="chapter" data-level="7.3.3" data-path="tidyverse.html"><a href="tidyverse.html#mutate-to-change-multiple-variables"><i class="fa fa-check"></i><b>7.3.3</b> Mutate to change multiple variables</a></li>
<li class="chapter" data-level="7.3.4" data-path="tidyverse.html"><a href="tidyverse.html#tidy_summ"><i class="fa fa-check"></i><b>7.3.4</b> Summarise as a unique form of mutate</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="tidyverse.html"><a href="tidyverse.html#pivoting_data"><i class="fa fa-check"></i><b>7.4</b> Wide and tall data</a><ul>
<li class="chapter" data-level="7.4.1" data-path="tidyverse.html"><a href="tidyverse.html#processing-data"><i class="fa fa-check"></i><b>7.4.1</b> Processing data</a></li>
<li class="chapter" data-level="7.4.2" data-path="tidyverse.html"><a href="tidyverse.html#pivot_longer"><i class="fa fa-check"></i><b>7.4.2</b> pivot_longer</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="tidyverse.html"><a href="tidyverse.html#pivot_wider"><i class="fa fa-check"></i><b>7.5</b> pivot_wider</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="trouble.html"><a href="trouble.html"><i class="fa fa-check"></i><b>8</b> Troubleshooting</a><ul>
<li class="chapter" data-level="8.1" data-path="trouble.html"><a href="trouble.html#working-independently"><i class="fa fa-check"></i><b>8.1</b> Working independently</a></li>
<li class="chapter" data-level="8.2" data-path="trouble.html"><a href="trouble.html#trouble_warnings"><i class="fa fa-check"></i><b>8.2</b> Common warnings</a></li>
<li class="chapter" data-level="8.3" data-path="trouble.html"><a href="trouble.html#trouble_errors"><i class="fa fa-check"></i><b>8.3</b> Common errors</a><ul>
<li class="chapter" data-level="8.3.1" data-path="trouble.html"><a href="trouble.html#object-not-found."><i class="fa fa-check"></i><b>8.3.1</b> Object not found.</a></li>
<li class="chapter" data-level="8.3.2" data-path="trouble.html"><a href="trouble.html#function-not-found"><i class="fa fa-check"></i><b>8.3.2</b> Function not found</a></li>
<li class="chapter" data-level="8.3.3" data-path="trouble.html"><a href="trouble.html#unexpected-symbols"><i class="fa fa-check"></i><b>8.3.3</b> Unexpected symbols</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="trouble.html"><a href="trouble.html#quick-warnings-and-errors"><i class="fa fa-check"></i><b>8.4</b> Quick warnings and errors</a></li>
<li class="chapter" data-level="8.5" data-path="trouble.html"><a href="trouble.html#searching-for-help"><i class="fa fa-check"></i><b>8.5</b> Searching for help</a><ul>
<li class="chapter" data-level="8.5.1" data-path="trouble.html"><a href="trouble.html#trouble_help"><i class="fa fa-check"></i><b>8.5.1</b> Tips for asking for help</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="trouble.html"><a href="trouble.html#trouble_reprex"><i class="fa fa-check"></i><b>8.6</b> Reproducible Examples (reprex)</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="statsbasic.html"><a href="statsbasic.html"><i class="fa fa-check"></i><b>9</b> Basic Statistics</a><ul>
<li class="chapter" data-level="9.1" data-path="statsbasic.html"><a href="statsbasic.html#descstats"><i class="fa fa-check"></i><b>9.1</b> Descriptive stats</a><ul>
<li class="chapter" data-level="9.1.1" data-path="statsbasic.html"><a href="statsbasic.html#mathematical-notation"><i class="fa fa-check"></i><b>9.1.1</b> Mathematical notation</a></li>
<li class="chapter" data-level="9.1.2" data-path="statsbasic.html"><a href="statsbasic.html#stats_mean"><i class="fa fa-check"></i><b>9.1.2</b> The mean</a></li>
<li class="chapter" data-level="9.1.3" data-path="statsbasic.html"><a href="statsbasic.html#the-mean-as-a-model"><i class="fa fa-check"></i><b>9.1.3</b> The mean as a model</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="statsbasic.html"><a href="statsbasic.html#stats_median"><i class="fa fa-check"></i><b>9.2</b> Median</a></li>
<li class="chapter" data-level="9.3" data-path="statsbasic.html"><a href="statsbasic.html#stats_mode"><i class="fa fa-check"></i><b>9.3</b> Mode</a></li>
<li class="chapter" data-level="9.4" data-path="statsbasic.html"><a href="statsbasic.html#stats_which"><i class="fa fa-check"></i><b>9.4</b> Which model?</a></li>
<li class="chapter" data-level="9.5" data-path="statsbasic.html"><a href="statsbasic.html#stats_variation"><i class="fa fa-check"></i><b>9.5</b> Measures of variation</a><ul>
<li class="chapter" data-level="9.5.1" data-path="statsbasic.html"><a href="statsbasic.html#stats_variance"><i class="fa fa-check"></i><b>9.5.1</b> Variance</a></li>
<li class="chapter" data-level="9.5.2" data-path="statsbasic.html"><a href="statsbasic.html#stats_sd"><i class="fa fa-check"></i><b>9.5.2</b> Standard Deviation</a></li>
<li class="chapter" data-level="9.5.3" data-path="statsbasic.html"><a href="statsbasic.html#stats_se"><i class="fa fa-check"></i><b>9.5.3</b> Standard Error</a></li>
</ul></li>
<li class="chapter" data-level="9.6" data-path="statsbasic.html"><a href="statsbasic.html#calculating-descriptive-stats"><i class="fa fa-check"></i><b>9.6</b> Calculating descriptive stats</a></li>
<li class="chapter" data-level="9.7" data-path="statsbasic.html"><a href="statsbasic.html#reporting-on-heifer-weight"><i class="fa fa-check"></i><b>9.7</b> Reporting on heifer weight</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="statsfreq.html"><a href="statsfreq.html"><i class="fa fa-check"></i><b>10</b> Predicting more things</a><ul>
<li class="chapter" data-level="10.1" data-path="statsfreq.html"><a href="statsfreq.html#ex_anovatheory"><i class="fa fa-check"></i><b>10.1</b> Partitioning Variation</a><ul>
<li class="chapter" data-level="10.1.1" data-path="statsfreq.html"><a href="statsfreq.html#perfect-worlds-vs-reality"><i class="fa fa-check"></i><b>10.1.1</b> Perfect Worlds vs Reality</a></li>
<li class="chapter" data-level="10.1.2" data-path="statsfreq.html"><a href="statsfreq.html#a-fake-experiment"><i class="fa fa-check"></i><b>10.1.2</b> A Fake Experiment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="choosestats.html"><a href="choosestats.html"><i class="fa fa-check"></i><b>11</b> How to choose your stats</a><ul>
<li class="chapter" data-level="11.1" data-path="choosestats.html"><a href="choosestats.html#cs_start"><i class="fa fa-check"></i><b>11.1</b> Where to start</a></li>
<li class="chapter" data-level="11.2" data-path="choosestats.html"><a href="choosestats.html#cs_rcat"><i class="fa fa-check"></i><b>11.2</b> My response is a categorical variable</a><ul>
<li class="chapter" data-level="11.2.1" data-path="choosestats.html"><a href="choosestats.html#cs_rcat_hist"><i class="fa fa-check"></i><b>11.2.1</b> Categorical Response, Historical/Known Comparisons</a></li>
<li class="chapter" data-level="11.2.2" data-path="choosestats.html"><a href="choosestats.html#cs_rcat_ecat"><i class="fa fa-check"></i><b>11.2.2</b> Categorical Response, Categorical Explanatory</a></li>
<li class="chapter" data-level="11.2.3" data-path="choosestats.html"><a href="choosestats.html#cs_rcat_enum"><i class="fa fa-check"></i><b>11.2.3</b> Categorical Response, Numerical Explanatory (Logistic Regression)</a></li>
</ul></li>
<li class="chapter" data-level="11.3" data-path="choosestats.html"><a href="choosestats.html#cs_rnum"><i class="fa fa-check"></i><b>11.3</b> My response is a numerical variable</a><ul>
<li class="chapter" data-level="11.3.1" data-path="choosestats.html"><a href="choosestats.html#cs_rnum_hist"><i class="fa fa-check"></i><b>11.3.1</b> Numerical Response, Historical/Known Comparisons (One Sample t-Test)</a></li>
<li class="chapter" data-level="11.3.2" data-path="choosestats.html"><a href="choosestats.html#cs_rnum_ecat_r"><i class="fa fa-check"></i><b>11.3.2</b> Numerical Response (Repeated Measures), Categorical Explanatory (Paired t-Test)</a></li>
<li class="chapter" data-level="11.3.3" data-path="choosestats.html"><a href="choosestats.html#cs_rnum_ecat"><i class="fa fa-check"></i><b>11.3.3</b> Numerical Response, Categorical Explanatory (ANOVA/GLM)</a></li>
<li class="chapter" data-level="11.3.4" data-path="choosestats.html"><a href="choosestats.html#cs_rnum_enum"><i class="fa fa-check"></i><b>11.3.4</b> Numerical Response, Numerical Explanatory (Correlation &amp; Regression)</a></li>
</ul></li>
<li class="chapter" data-level="11.4" data-path="choosestats.html"><a href="choosestats.html#my-response-is-an-ordinal-variable-cs_rord"><i class="fa fa-check"></i><b>11.4</b> My response is an ordinal variable {cs_rord}</a><ul>
<li class="chapter" data-level="11.4.1" data-path="choosestats.html"><a href="choosestats.html#cs_rord_hist"><i class="fa fa-check"></i><b>11.4.1</b> Ordinal Response, Historical/Known Comparisons (One Sample Wilcoxan Test)</a></li>
<li class="chapter" data-level="11.4.2" data-path="choosestats.html"><a href="choosestats.html#cs_rord_ecat_r"><i class="fa fa-check"></i><b>11.4.2</b> Ordinal Response (Repeated Measures), Categorical Explanatory (One Sample Wilcoxan Signed-Rank Test)</a></li>
<li class="chapter" data-level="11.4.3" data-path="choosestats.html"><a href="choosestats.html#cs_rord_ecat"><i class="fa fa-check"></i><b>11.4.3</b> Ordinal Response, Categorical Explanatory</a></li>
<li class="chapter" data-level="11.4.4" data-path="choosestats.html"><a href="choosestats.html#cs_rord_rnum"><i class="fa fa-check"></i><b>11.4.4</b> Ordinal Response, Numerical Explanatory (Spearman rank correlation)</a></li>
</ul></li>
<li class="chapter" data-level="11.5" data-path="choosestats.html"><a href="choosestats.html#cs_glms"><i class="fa fa-check"></i><b>11.5</b> I got all of them (generalised linear model)</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="whatnext.html"><a href="whatnext.html"><i class="fa fa-check"></i><b>12</b> What next</a><ul>
<li class="chapter" data-level="12.1" data-path="whatnext.html"><a href="whatnext.html#github"><i class="fa fa-check"></i><b>12.1</b> github</a></li>
<li class="chapter" data-level="12.2" data-path="whatnext.html"><a href="whatnext.html#experiment-and-build"><i class="fa fa-check"></i><b>12.2</b> Experiment and build</a></li>
<li class="chapter" data-level="12.3" data-path="whatnext.html"><a href="whatnext.html#the-r-community"><i class="fa fa-check"></i><b>12.3</b> The R Community</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="whyr.html"><a href="whyr.html"><i class="fa fa-check"></i><b>13</b> Why use R</a><ul>
<li class="chapter" data-level="13.1" data-path="whyr.html"><a href="whyr.html#why-does-open-source-matter"><i class="fa fa-check"></i><b>13.1</b> Why does open source matter?</a></li>
<li class="chapter" data-level="13.2" data-path="whyr.html"><a href="whyr.html#so-why-r"><i class="fa fa-check"></i><b>13.2</b> So why R?</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="answers.html"><a href="answers.html"><i class="fa fa-check"></i><b>14</b> Answers</a><ul>
<li class="chapter" data-level="14.1" data-path="answers.html"><a href="answers.html#ans_createdata"><i class="fa fa-check"></i><b>14.1</b> Creating Data Answers</a><ul>
<li class="chapter" data-level="14.1.1" data-path="answers.html"><a href="answers.html#changing-mpg-data"><i class="fa fa-check"></i><b>14.1.1</b> Changing mpg data</a></li>
</ul></li>
<li class="chapter" data-level="14.2" data-path="answers.html"><a href="answers.html#ans_loadcsv"><i class="fa fa-check"></i><b>14.2</b> Loading csv data answers</a></li>
<li class="chapter" data-level="14.3" data-path="answers.html"><a href="answers.html#ans_loadexcel"><i class="fa fa-check"></i><b>14.3</b> Loading excel data answers</a></li>
<li class="chapter" data-level="14.4" data-path="answers.html"><a href="answers.html#ans_ggbox"><i class="fa fa-check"></i><b>14.4</b> ggplot answers</a><ul>
<li class="chapter" data-level="14.4.1" data-path="answers.html"><a href="answers.html#boxplot-of-highway-miles-per-gallon-versus-class-mpg-dataset"><i class="fa fa-check"></i><b>14.4.1</b> Boxplot of highway miles per gallon versus class (mpg dataset)</a></li>
<li class="chapter" data-level="14.4.2" data-path="answers.html"><a href="answers.html#ans_gghist"><i class="fa fa-check"></i><b>14.4.2</b> Histogram of city miles per gallon faceted by transmission type (mpg dataset)</a></li>
</ul></li>
<li class="chapter" data-level="14.5" data-path="answers.html"><a href="answers.html#stats_proofvariance"><i class="fa fa-check"></i><b>14.5</b> Proof of variance</a></li>
<li class="chapter" data-level="14.6" data-path="answers.html"><a href="answers.html#ans_tidyunicorns"><i class="fa fa-check"></i><b>14.6</b> Tidy Unicorns</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="acks.html"><a href="acks.html"><i class="fa fa-check"></i><b>15</b> Acknowledgements</a><ul>
<li class="chapter" data-level="15.1" data-path="acks.html"><a href="acks.html#image-sources"><i class="fa fa-check"></i><b>15.1</b> Image Sources</a></li>
<li class="chapter" data-level="15.2" data-path="acks.html"><a href="acks.html#specific-acknowledgements"><i class="fa fa-check"></i><b>15.2</b> Specific Acknowledgements</a></li>
<li class="chapter" data-level="15.3" data-path="acks.html"><a href="acks.html#beta-testers-and-helpers"><i class="fa fa-check"></i><b>15.3</b> Beta Testers and Helpers</a></li>
<li class="chapter" data-level="15.4" data-path="acks.html"><a href="acks.html#the-biggest-thanks"><i class="fa fa-check"></i><b>15.4</b> The biggest thanks</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R @ R(D)SVS</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="statsfreq" class="section level1">
<h1><span class="header-section-number">Chapter 10</span> Predicting more things</h1>
<div class="los">
<p>
You can skip this chapter if . . .
</p>
<ul>
<li>
<p>
You can describe the basic theory of partitioning variation
</p>
</li>
<li>
<p>
You can run an ANOVA or glm in R
</p>
</li>
</ul>
</div>
<div id="ex_anovatheory" class="section level2">
<h2><span class="header-section-number">10.1</span> Partitioning Variation</h2>
<p>In the previous chapter, we spent a lot of time defining <a href="statsbasic.html#stats_variance">variance</a>. Part of the reason why we spent so much time on it is because its key to understanding how some more complicated statistics work.</p>
<p>Much of this section is taken from <a href="https://global.oup.com/uk/orc/biosciences/maths/grafen/">Grafe &amp; Hails’ Modern Statistics for the Life Sciences</a> which I think is a great stats book. If you’re enjoying statistics, or want more detail than is in these pages, its one that I personally used a lot when I was learning.</p>
<p>In this exercise, we’re going to spend more time thinking about variance - and we need to have <code>tidyverse</code> loaded, so you know what to do:</p>
<div class="sourceCode" id="cb140"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb140-1"><a href="statsfreq.html#cb140-1"></a><span class="kw">library</span>(tidyverse)</span></code></pre></div>
<div id="perfect-worlds-vs-reality" class="section level3">
<h3><span class="header-section-number">10.1.1</span> Perfect Worlds vs Reality</h3>
<p>Let’s think a little bit about what we mean by this question: <strong>does x affect y?</strong></p>
<p>We want to know what proportion of the variation we observe in <strong>y</strong> can be explained by <strong>x</strong>.</p>
<p>To do this, we want to think about a perfect example where <strong>all</strong> of the variation in <strong>y</strong> can be explained by <strong>x</strong>.</p>
<p>Let’s create some data:</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="statsfreq.html#cb141-1"></a>examples &lt;-<span class="st"> </span><span class="kw">tibble</span> (<span class="dt">x.perfect =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">9</span>,<span class="dv">10</span>), </span>
<span id="cb141-2"><a href="statsfreq.html#cb141-2"></a>                    <span class="dt">y.perfect =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">9</span>,<span class="dv">10</span>), </span>
<span id="cb141-3"><a href="statsfreq.html#cb141-3"></a>                    <span class="dt">x.realistic =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">8</span>,<span class="dv">8</span>,<span class="dv">9</span>,<span class="dv">11</span>), </span>
<span id="cb141-4"><a href="statsfreq.html#cb141-4"></a>                    <span class="dt">y.realistic =</span> <span class="kw">c</span>(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">8</span>, <span class="dv">9</span>, <span class="dv">9</span>))</span></code></pre></div>
<p>First, let’s visualise the perfect world:</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="statsfreq.html#cb142-1"></a>examples <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb142-2"><a href="statsfreq.html#cb142-2"></a><span class="st">  </span><span class="kw">ggplot</span> (<span class="kw">aes</span>(<span class="dt">x =</span> x.perfect, <span class="dt">y =</span> y.perfect))<span class="op">+</span></span>
<span id="cb142-3"><a href="statsfreq.html#cb142-3"></a><span class="st">  </span><span class="kw">geom_point</span> () <span class="op">+</span></span>
<span id="cb142-4"><a href="statsfreq.html#cb142-4"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">10</span>)) <span class="op">+</span></span>
<span id="cb142-5"><a href="statsfreq.html#cb142-5"></a><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">10</span>)) <span class="op">+</span></span>
<span id="cb142-6"><a href="statsfreq.html#cb142-6"></a><span class="st">  </span><span class="kw">labs</span> (<span class="dt">title =</span> <span class="st">&quot;100% of the variation in y is explained by x&quot;</span>) <span class="op">+</span></span>
<span id="cb142-7"><a href="statsfreq.html#cb142-7"></a><span class="st">  </span><span class="kw">theme_classic</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-213"></span>
<img src="ratrdsvs_files/figure-html/unnamed-chunk-213-1.png" alt="100% of the variation in y is explained by x" width="672" />
<p class="caption">
Figure: 10.1: 100% of the variation in y is explained by x
</p>
</div>
<p>In a ‘perfect’ dataset, we see that for every unit increase in x, y increases by the same. There’s a 1:1 relationship between the two.</p>
<p>Of course, we very rarely ever see this in the real world.</p>
<p>How does it look with (slightly) more realistic data?</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="statsfreq.html#cb143-1"></a>examples <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb143-2"><a href="statsfreq.html#cb143-2"></a><span class="st">  </span><span class="kw">ggplot</span> (<span class="kw">aes</span>(<span class="dt">x =</span> x.realistic, <span class="dt">y =</span> y.realistic))<span class="op">+</span></span>
<span id="cb143-3"><a href="statsfreq.html#cb143-3"></a><span class="st">  </span><span class="kw">geom_point</span> () <span class="op">+</span></span>
<span id="cb143-4"><a href="statsfreq.html#cb143-4"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">10</span>)) <span class="op">+</span></span>
<span id="cb143-5"><a href="statsfreq.html#cb143-5"></a><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">10</span>)) <span class="op">+</span></span>
<span id="cb143-6"><a href="statsfreq.html#cb143-6"></a><span class="st">  </span><span class="kw">labs</span> (<span class="dt">title =</span> <span class="st">&quot;How much of the variation in y is explained by x?&quot;</span>) <span class="op">+</span></span>
<span id="cb143-7"><a href="statsfreq.html#cb143-7"></a><span class="st">  </span><span class="kw">theme_classic</span>()</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-214"></span>
<img src="ratrdsvs_files/figure-html/unnamed-chunk-214-1.png" alt="A more realistic example" width="672" />
<p class="caption">
Figure: 10.2: A more realistic example
</p>
</div>
<p>Most of us looking at this chart would be able to draw a ‘line of best fit’ describing the relationship between x and y in this example. With a linear model we can calculate this exactly.</p>
<p>This is the exact same equation as you would have learned at school:</p>
<p><span class="math display">\[ y = mx + c \]</span></p>
<p>or</p>
<p>predicted y = gradient * (a value of x) + y intercept</p>
<p>We can ask R to fit a linear model for this data. The function <code>lm</code> asks for a <code>formula</code> argument which looks like <code>y ~ x</code>. The formula is a bit unusual in terms of R language because there are no ‘placeholder’ or ‘default’ values, meaning we can’t type <code>y = y.realistic</code> here. The <code>lm</code> function is part of R’s basic stats code (meaning we don’t need to load any particular library to use it).</p>
<pre><code>## 
## Call:
## lm(formula = y.realistic ~ x.realistic, data = examples)
## 
## Coefficients:
## (Intercept)  x.realistic  
##      1.3659       0.7561</code></pre>
<p>The output here starts with the <strong>Call</strong> which reiterates what we specificed in our <code>lm</code> command. Then it gives us:</p>
<ul>
<li><p>Coefficient of the intercept (where our model line crosses the y axis)</p></li>
<li><p>Coefficient of x.realistic</p></li>
</ul>
<p>Since x.realistic is a continuous variable, the x.realistic coeffcient represents the difference in the predicted value of Y for each one-unit difference in x.realistic.</p>
<p>If that’s confusing, let’s run this on the perfect data:</p>
<pre><code>## 
## Call:
## lm(formula = y.perfect ~ x.perfect, data = examples)
## 
## Coefficients:
## (Intercept)    x.perfect  
##   1.123e-15    1.000e+00</code></pre>
<p>The coefficient for x.perfect is 1. For every 1 step increase in the value of x, our value of y increases by 1.</p>
<p>Our coefficient is very nearly zero (it’s not exactly zero because of a thing called <a href="https://0.30000000000000004.com/">floating point math</a> which is kind of interesting but not super relevant).</p>
<p>We could plug this in to our equation above to predict a value of y. The coefficient of x is the same as the gradient in a simple linear model, and so we can predict y when x = 3:</p>
<p><span class="math display">\[ y = mx + c \]</span></p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="statsfreq.html#cb146-1"></a>predict.perfect.y =<span class="st"> </span><span class="dv">1</span> <span class="op">*</span><span class="st"> </span><span class="dv">3</span> <span class="op">+</span><span class="st"> </span><span class="dv">0</span></span>
<span id="cb146-2"><a href="statsfreq.html#cb146-2"></a></span>
<span id="cb146-3"><a href="statsfreq.html#cb146-3"></a>predict.perfect.y</span></code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>Perfect!</p>
<p>What if we try our realistic data? If you <code>View(examples)</code> you can see that when x.realistic = 3, y.realistic = 4. Does our linear model predict this?</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="statsfreq.html#cb148-1"></a>predict.realistic.y =<span class="st"> </span><span class="fl">0.7561</span> <span class="op">*</span><span class="st"> </span><span class="dv">3</span> <span class="op">+</span><span class="st"> </span><span class="fl">1.3659</span></span>
<span id="cb148-2"><a href="statsfreq.html#cb148-2"></a></span>
<span id="cb148-3"><a href="statsfreq.html#cb148-3"></a>predict.realistic.y</span></code></pre></div>
<pre><code>## [1] 3.6342</code></pre>
<p>… Sort of? It doesn’t predict it perfectly, but its pretty close . . .</p>
<p>You might now be wondering, is this significant? You’ll have heard scientists talk about significance a lot. Well, we can find this out by asking R to summarise the model:</p>
<pre><code>## 
## Call:
## lm(formula = y.realistic ~ x.realistic, data = examples)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -0.9024 -0.6159  0.1220  0.6037  0.8293 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  1.36585    0.46584   2.932   0.0189 *  
## x.realistic  0.75610    0.07258  10.418 6.25e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.7199 on 8 degrees of freedom
## Multiple R-squared:  0.9314,	Adjusted R-squared:  0.9228 
## F-statistic: 108.5 on 1 and 8 DF,  p-value: 6.247e-06</code></pre>
<p>This time we get more information. The coefficients are still listed in the table, alongside their standard error, a T Value and a P value. The P value is very small, much smaller than the cut-off of p&lt;0.05. Therefore we must say this is a significant result?</p>
<p>At the top we have residuals which we’ll come to another day, and at the bottom we have an F statistic and a P Value (these are the ones I’d pay attention to if I were you) and an Adjusted R-squared. At the moment this tell us that 92% of the variation in y.realistic can be explained by x.realistic.</p>
<p>And if we wanted, we could add this to our plot from earlier with the addition of a single line of code:</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="statsfreq.html#cb151-1"></a>examples <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb151-2"><a href="statsfreq.html#cb151-2"></a><span class="st">  </span><span class="kw">ggplot</span> (<span class="kw">aes</span>(<span class="dt">x =</span> x.realistic, <span class="dt">y =</span> y.realistic))<span class="op">+</span></span>
<span id="cb151-3"><a href="statsfreq.html#cb151-3"></a><span class="st">  </span><span class="kw">geom_point</span> () <span class="op">+</span></span>
<span id="cb151-4"><a href="statsfreq.html#cb151-4"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">10</span>)) <span class="op">+</span></span>
<span id="cb151-5"><a href="statsfreq.html#cb151-5"></a><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">10</span>)) <span class="op">+</span></span>
<span id="cb151-6"><a href="statsfreq.html#cb151-6"></a><span class="st">  </span><span class="kw">labs</span> (<span class="dt">title =</span> <span class="st">&quot;How much of the variation in y is explained by x?&quot;</span>) <span class="op">+</span></span>
<span id="cb151-7"><a href="statsfreq.html#cb151-7"></a><span class="st">  </span><span class="kw">theme_classic</span>() <span class="op">+</span><span class="st"> </span><span class="co"># And add a single line below:</span></span>
<span id="cb151-8"><a href="statsfreq.html#cb151-8"></a><span class="st">  </span><span class="kw">geom_smooth</span> (<span class="dt">method =</span> <span class="st">&#39;lm&#39;</span>) </span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-220"></span>
<img src="ratrdsvs_files/figure-html/unnamed-chunk-220-1.png" alt="y.realstic and x.realistic with a fit line" width="672" />
<p class="caption">
Figure: 10.3: y.realstic and x.realistic with a fit line
</p>
</div>
<p>If we were reporting this we would say that:</p>
<blockquote>
<p>y.realistic increased with x.realistic. A linear model predicted that for every unit increase in x.realistic, y.realistic would increase by 0.76, and this explained 93% of the variation observed in y.realistic (F<sup>1,8</sup> = 108.5, p &lt; 0.001, Figure 10.3)</p>
</blockquote>
<p>But what do all these numbers mean? That’s what we’re going to look at:</p>
</div>
<div id="a-fake-experiment" class="section level3">
<h3><span class="header-section-number">10.1.2</span> A Fake Experiment</h3>
<p>We’re going to start with a fake experiment to explore this. As you may know, the national animal of Scotland is the unicorn. In our example, Scotland has started farming unicorns (in a very welfare friendly manner, of course) to export more magic dust. Unicorns shed magic dust from their horns every morning, and this is gathered by the farmer.</p>
<p>There’s a belief that unicorns shed more dust when they hear music, and so we set up a trial with three farms:</p>
<ul>
<li><p>Farm 1 was our negative control farm, with no intervention.</p></li>
<li><p>Farm 2 was our trial farm, where a radio station tuned to music was played over the speakers.</p></li>
<li><p>Farm 3 was a positive control farm, and played radio tuned to BBC Radio 4 for thoughtful discussion.</p></li>
</ul>
<p>We recorded the raw weekly dust yield of 10 unicorns on each farm, and the data looks like this:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="statsfreq.html#cb152-1"></a>Radio &lt;-<span class="st"> </span><span class="kw">tibble</span> (<span class="dt">NoRadio =</span> <span class="kw">c</span>(<span class="dv">150</span>, <span class="dv">130</span>, <span class="dv">121</span>, <span class="dv">90</span>, <span class="dv">98</span>, <span class="dv">100</span>, <span class="dv">98</span>, <span class="dv">100</span>, <span class="dv">113</span>, <span class="dv">111</span>),</span>
<span id="cb152-2"><a href="statsfreq.html#cb152-2"></a>                 <span class="dt">RadioMusic =</span> <span class="kw">c</span>(<span class="dv">112</span>, <span class="dv">127</span>, <span class="dv">132</span>, <span class="dv">150</span>, <span class="dv">112</span>, <span class="dv">128</span>, <span class="dv">110</span>, <span class="dv">120</span>, <span class="dv">98</span>, <span class="dv">107</span>),</span>
<span id="cb152-3"><a href="statsfreq.html#cb152-3"></a>                 <span class="dt">RadioDiscussion =</span> <span class="kw">c</span>(<span class="dv">75</span>, <span class="dv">98</span>, <span class="dv">88</span>, <span class="dv">83</span>, <span class="dv">83</span>, <span class="dv">77</span>, <span class="dv">75</span>, <span class="dv">84</span>, <span class="dv">93</span>, <span class="dv">99</span>))</span></code></pre></div>
<p>In the majority of our experiments and statistical analyses, we always want to know <strong>Does x affect y?</strong>.</p>
<p>In this case, we’re asking: <strong>Does radio as a background noise affect the magic dust yield of unicorns?</strong></p>
<div id="ex_tidyunicorns" class="section level4">
<h4><span class="header-section-number">10.1.2.1</span> Tidying this data</h4>
<p>Remember that we want data to be tidy. We should <a href="tidyverse.html#pivoting_data">pivot</a> this data so every row is an observation of a unicorn.</p>
<p>Try creating a new dataset caled <code>RadioTidy</code> yourself. <code>RadioTidy</code> should have two columns named “Radio” and “DustYield”. You can check your work in the <a href="answers.html#ans_tidyunicorns">answers</a></p>
<div class="hey">
<p>
If you use your own solution to tidy the data remember that R is case sensitive. I have called the columns <strong>Radio</strong> and <strong>DustYield</strong>. If your data isn’t named in the same way copying and pasting the following code chunks will give you errors.
</p>
</div>
</div>
<div id="visualising-our-unicorns" class="section level4">
<h4><span class="header-section-number">10.1.2.2</span> Visualising our unicorns</h4>
<p>We know we should start by visualising our data, but in this example I’m going to visualise it in a few different ways. You wouldn’t normally do this, but I’m trying to demonstrate some things about variance.</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="statsfreq.html#cb153-1"></a>RadioTidy <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb153-2"><a href="statsfreq.html#cb153-2"></a><span class="st">  </span><span class="kw">ggplot</span> (<span class="kw">aes</span> (<span class="dt">x =</span> Radio, <span class="dt">y =</span> DustYield)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb153-3"><a href="statsfreq.html#cb153-3"></a><span class="st">     </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">shape =</span> Radio, <span class="dt">colour =</span> Radio)) <span class="op">+</span></span>
<span id="cb153-4"><a href="statsfreq.html#cb153-4"></a><span class="st">     </span><span class="kw">labs</span> (<span class="dt">y =</span> <span class="st">&quot;Dust Yield (Kg)&quot;</span>, <span class="dt">x =</span> <span class="st">&quot;Radio Condition&quot;</span>) <span class="op">+</span></span>
<span id="cb153-5"><a href="statsfreq.html#cb153-5"></a><span class="st">     </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">200</span>)) <span class="op">+</span></span>
<span id="cb153-6"><a href="statsfreq.html#cb153-6"></a><span class="st">     </span><span class="kw">theme_classic</span> ()</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-224"></span>
<img src="ratrdsvs_files/figure-html/unnamed-chunk-224-1.png" alt="Magic Dust Yield (kg) by Unicorn Farm" width="672" />
<p class="caption">
Figure: 10.4: Magic Dust Yield (kg) by Unicorn Farm
</p>
</div>
<p>In this chart we have plotted the yield of every single unicorn by farm. We still want to know whether radio affects yield, but we know that some unicorns are probably high dust yielders, and others might be low yielding unicorns. In other words, we know that individuals vary, and so we want to know what happens to the group on average.</p>
<p>But we can also see here that the groups seem to be different. The amount of variation isn’t the same between the groups. In fact, the farm ‘Radio Discussion’ is more closely clustered together than the others.</p>
<p>The variance of a dataset describes how much the data is scattered around the mean. An ANOVA is simply asking:
&gt;Is the mean of each group a better predictor than the mean of all the data?.</p>
<p>Let’s start by looking at only one farm (note - you wouldn’t be likely to do this in a real life example, this is for explanation purposes only):</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="statsfreq.html#cb154-1"></a>Radio <span class="op">%&gt;%</span></span>
<span id="cb154-2"><a href="statsfreq.html#cb154-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">UnicornNo =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">9</span>,<span class="dv">10</span>)) <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb154-3"><a href="statsfreq.html#cb154-3"></a><span class="st">  </span><span class="co"># The mutate function adds a new variable just to plot this one specific chart</span></span>
<span id="cb154-4"><a href="statsfreq.html#cb154-4"></a><span class="st">  </span><span class="co"># And then we pipe it directly into ggplot, so we&#39;re not changing the Radio data</span></span>
<span id="cb154-5"><a href="statsfreq.html#cb154-5"></a><span class="st">  </span><span class="co"># Remember you can check this with `View(Radio)`, you&#39;ll see &#39;UnicornNo&#39; doesn&#39;t exist.</span></span>
<span id="cb154-6"><a href="statsfreq.html#cb154-6"></a><span class="st">  </span><span class="kw">ggplot</span> (<span class="kw">aes</span> (<span class="dt">x =</span> UnicornNo, <span class="dt">y =</span> NoRadio)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb154-7"><a href="statsfreq.html#cb154-7"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb154-8"><a href="statsfreq.html#cb154-8"></a><span class="st">  </span><span class="kw">labs</span> (<span class="dt">y =</span> <span class="st">&quot;Dust Yield (Kg)&quot;</span>) <span class="op">+</span></span>
<span id="cb154-9"><a href="statsfreq.html#cb154-9"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">200</span>)) <span class="op">+</span></span>
<span id="cb154-10"><a href="statsfreq.html#cb154-10"></a><span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">breaks =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">8</span>, <span class="dv">10</span>)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb154-11"><a href="statsfreq.html#cb154-11"></a><span class="st">  </span><span class="kw">theme_classic</span> ()</span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-225"></span>
<img src="ratrdsvs_files/figure-html/unnamed-chunk-225-1.png" alt="Magic dust yield (kg) for Farm 1" width="672" />
<p class="caption">
Figure: 10.5: Magic dust yield (kg) for Farm 1
</p>
</div>
<p>Deviations from the mean will be both positive and negative, and the sum of these deviations will always be zero. First, let’s find out the mean dust yield of the farm without any radio . . .</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="statsfreq.html#cb155-1"></a>RadioTidy <span class="op">%&gt;%</span></span>
<span id="cb155-2"><a href="statsfreq.html#cb155-2"></a><span class="st">  </span><span class="kw">group_by</span>(Radio) <span class="op">%&gt;%</span></span>
<span id="cb155-3"><a href="statsfreq.html#cb155-3"></a><span class="st">  </span><span class="kw">filter</span>(Radio <span class="op">==</span><span class="st"> &quot;NoRadio&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb155-4"><a href="statsfreq.html#cb155-4"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean =</span> <span class="kw">mean</span>(DustYield))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 2
##   Radio    mean
##   &lt;chr&gt;   &lt;dbl&gt;
## 1 NoRadio  111.</code></pre>
<p>We could plot this mean on our chart with an extra line of code:</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="statsfreq.html#cb157-1"></a>Radio <span class="op">%&gt;%</span></span>
<span id="cb157-2"><a href="statsfreq.html#cb157-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">count =</span> <span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">9</span>,<span class="dv">10</span>)) <span class="op">%&gt;%</span></span>
<span id="cb157-3"><a href="statsfreq.html#cb157-3"></a><span class="st">  </span><span class="kw">ggplot</span> (<span class="kw">aes</span> (<span class="dt">x =</span> count, <span class="dt">y =</span> NoRadio)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb157-4"><a href="statsfreq.html#cb157-4"></a><span class="st">  </span><span class="kw">geom_point</span>() <span class="op">+</span></span>
<span id="cb157-5"><a href="statsfreq.html#cb157-5"></a><span class="st">  </span><span class="kw">labs</span> (<span class="dt">y =</span> <span class="st">&quot;Dust Yield (Kg)&quot;</span>) <span class="op">+</span></span>
<span id="cb157-6"><a href="statsfreq.html#cb157-6"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">200</span>)) <span class="op">+</span></span>
<span id="cb157-7"><a href="statsfreq.html#cb157-7"></a><span class="st">  </span><span class="kw">theme_classic</span> () <span class="op">+</span></span>
<span id="cb157-8"><a href="statsfreq.html#cb157-8"></a><span class="st">  </span><span class="co"># This new line basically draws a line on our chart based on the mean we just calculated</span></span>
<span id="cb157-9"><a href="statsfreq.html#cb157-9"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="fl">111.1</span>) </span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:unnamed-chunk-227"></span>
<img src="ratrdsvs_files/figure-html/unnamed-chunk-227-1.png" alt="Magic dust yield (kg) for Farm 1, Mean Line Added" width="672" />
<p class="caption">
Figure: 10.6: Magic dust yield (kg) for Farm 1, Mean Line Added
</p>
</div>
</div>
<div id="deviation-from-the-group-mean" class="section level4">
<h4><span class="header-section-number">10.1.2.3</span> Deviation from the group mean</h4>
<p>We want to know what the deviation from the mean of the group is for each individual. We can ask R to calculate this for us using the handy mutate function:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="statsfreq.html#cb158-1"></a>Radio <span class="op">%&gt;%</span></span>
<span id="cb158-2"><a href="statsfreq.html#cb158-2"></a><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">NoRadioDeviation =</span> (<span class="kw">mean</span>(NoRadio) <span class="op">-</span><span class="st"> </span>NoRadio)) </span></code></pre></div>
<pre><code>## # A tibble: 10 x 4
##    NoRadio RadioMusic RadioDiscussion NoRadioDeviation
##      &lt;dbl&gt;      &lt;dbl&gt;           &lt;dbl&gt;            &lt;dbl&gt;
##  1     150        112              75          -38.9  
##  2     130        127              98          -18.9  
##  3     121        132              88           -9.9  
##  4      90        150              83           21.1  
##  5      98        112              83           13.1  
##  6     100        128              77           11.1  
##  7      98        110              75           13.1  
##  8     100        120              84           11.1  
##  9     113         98              93           -1.9  
## 10     111        107              99            0.100</code></pre>
<p>You can check that the sum of NoRadioDeviation does add to zero (or at least very close to it given some rounding errors because of floating point math):</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="statsfreq.html#cb160-1"></a>Radio <span class="op">%&gt;%</span></span>
<span id="cb160-2"><a href="statsfreq.html#cb160-2"></a><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">NoRadioDeviation =</span> (<span class="kw">mean</span>(NoRadio) <span class="op">-</span><span class="st"> </span>NoRadio)) <span class="op">%&gt;%</span></span>
<span id="cb160-3"><a href="statsfreq.html#cb160-3"></a><span class="st">  </span><span class="kw">summarise</span> (<span class="st">&quot;Sum of Deviations from No Radio Mean&quot;</span> =<span class="st"> </span><span class="kw">sum</span>(NoRadioDeviation))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   `Sum of Deviations from No Radio Mean`
##                                    &lt;dbl&gt;
## 1                    -0.0000000000000568</code></pre>
<div class="hey">
<p>
No matter what your dataset looks like, no matter what numbers are in there, this will always be true.
</p>
</div>
</div>
<div id="calculating-variance-from-deviations" class="section level4">
<h4><span class="header-section-number">10.1.2.4</span> Calculating variance from deviations</h4>
<p>Because the deviations will always sum to 0, the raw deviations are not very useful.</p>
<p>So how can we compare the deviation (variance) between two datasets?</p>
<p>If we square the deviations and then sum them we have a more useful measure of variance that we call Sums of Squares (SS)</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="statsfreq.html#cb162-1"></a>Radio <span class="op">%&gt;%</span></span>
<span id="cb162-2"><a href="statsfreq.html#cb162-2"></a><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">NoRadioDeviation =</span> (<span class="kw">mean</span>(NoRadio) <span class="op">-</span><span class="st"> </span>NoRadio),</span>
<span id="cb162-3"><a href="statsfreq.html#cb162-3"></a>          <span class="dt">SquaredNoRadioDeviation =</span> (NoRadioDeviation<span class="op">*</span>NoRadioDeviation))</span></code></pre></div>
<pre><code>## # A tibble: 10 x 5
##    NoRadio RadioMusic RadioDiscussion NoRadioDeviation SquaredNoRadioDeviation
##      &lt;dbl&gt;      &lt;dbl&gt;           &lt;dbl&gt;            &lt;dbl&gt;                   &lt;dbl&gt;
##  1     150        112              75          -38.9                 1513.    
##  2     130        127              98          -18.9                  357.    
##  3     121        132              88           -9.9                   98.0   
##  4      90        150              83           21.1                  445.    
##  5      98        112              83           13.1                  172.    
##  6     100        128              77           11.1                  123.    
##  7      98        110              75           13.1                  172.    
##  8     100        120              84           11.1                  123.    
##  9     113         98              93           -1.9                    3.61  
## 10     111        107              99            0.100                  0.0100</code></pre>
<p>Sums of Squares are useful because they don’t sum to 0, but they’re still influenced by the number of data points we have (e.g. if we had one more unicorn in the No Radio farm the sum of squares would have to increase).</p>
<p>So we calculate the variance of the dataset by:</p>
<p><span class="math display">\[\sigma^2 = \frac{SumsofSquares}{n-1} \]</span> $$</p>
<p>Variance is therefore a measure of the variability of a dataset that takes the size of the dataset into account. And we can use variance to compare variability across different datasets. It’s very useful!</p>
<p>R, we know, has a very handy function to calculate variance automatically:</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="statsfreq.html#cb164-1"></a>Radio <span class="op">%&gt;%</span></span>
<span id="cb164-2"><a href="statsfreq.html#cb164-2"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="st">&quot;Variance No Radio&quot;</span> =<span class="st"> </span><span class="kw">var</span>(NoRadio))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   `Variance No Radio`
##                 &lt;dbl&gt;
## 1                334.</code></pre>
<p>But if you’re not convinced . . .</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="statsfreq.html#cb166-1"></a>Radio <span class="op">%&gt;%</span></span>
<span id="cb166-2"><a href="statsfreq.html#cb166-2"></a><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">NoRadioDeviation =</span> (<span class="kw">mean</span>(NoRadio) <span class="op">-</span><span class="st"> </span>NoRadio),</span>
<span id="cb166-3"><a href="statsfreq.html#cb166-3"></a>          <span class="dt">SquaredNoRadioDeviation =</span> (NoRadioDeviation<span class="op">*</span>NoRadioDeviation)) <span class="op">%&gt;%</span></span>
<span id="cb166-4"><a href="statsfreq.html#cb166-4"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">SumSquaresNoRadio =</span> <span class="kw">sum</span>(SquaredNoRadioDeviation))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##   SumSquaresNoRadio
##               &lt;dbl&gt;
## 1             3007.</code></pre>
<p>And then divide that by <code>n-1</code>:</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="statsfreq.html#cb168-1"></a><span class="fl">3006.9</span><span class="op">/</span><span class="dv">9</span></span></code></pre></div>
<pre><code>## [1] 334.1</code></pre>
</div>
<div id="partitioning-variation" class="section level4">
<h4><span class="header-section-number">10.1.2.5</span> Partitioning Variation</h4>
<p>Remember, in this experiment we can see that there is variation around dust yields. What we want to know is:</p>
<ul>
<li><p>How much of this variation is due to our explanatory variable (what kind of radio they listened to)</p></li>
<li><p><strong>How does x affect y?</strong></p></li>
</ul>
<div id="imaginary-scenario-1" class="section level5">
<h5><span class="header-section-number">10.1.2.5.1</span> Imaginary Scenario 1</h5>
<p>Let’s imagine a scenario where the condition (our categorical variable) explains almost all of the variance in the dataset.</p>
<p>It would look like this:</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="statsfreq.html#cb170-1"></a>Sce1 &lt;-<span class="st"> </span><span class="kw">tibble</span> (<span class="dt">Condition1 =</span> <span class="kw">c</span>(<span class="dv">99</span>,<span class="dv">100</span>,<span class="dv">101</span>,<span class="dv">99</span>,<span class="dv">100</span>,<span class="dv">101</span>,<span class="dv">99</span>,<span class="dv">101</span>,<span class="dv">100</span>,<span class="dv">101</span>),</span>
<span id="cb170-2"><a href="statsfreq.html#cb170-2"></a>              <span class="dt">Condition2 =</span> <span class="kw">c</span>(<span class="dv">120</span>,<span class="dv">121</span>,<span class="dv">122</span>,<span class="dv">120</span>,<span class="dv">121</span>,<span class="dv">122</span>,<span class="dv">120</span>,<span class="dv">123</span>,<span class="dv">121</span>,<span class="dv">120</span>),</span>
<span id="cb170-3"><a href="statsfreq.html#cb170-3"></a>              <span class="dt">Condition3 =</span> <span class="kw">c</span>(<span class="dv">83</span>,<span class="dv">84</span>,<span class="dv">85</span>,<span class="dv">85</span>,<span class="dv">84</span>,<span class="dv">83</span>,<span class="dv">83</span>,<span class="dv">84</span>,<span class="dv">85</span>,<span class="dv">86</span>)) <span class="op">%&gt;%</span></span>
<span id="cb170-4"><a href="statsfreq.html#cb170-4"></a><span class="st">  </span><span class="kw">pivot_longer</span> (<span class="dt">cols =</span> <span class="kw">c</span>(Condition1<span class="op">:</span>Condition3), <span class="dt">names_to =</span> <span class="st">&quot;Condition&quot;</span>, <span class="dt">values_to =</span> <span class="st">&quot;DustYield&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb170-5"><a href="statsfreq.html#cb170-5"></a><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">Count =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">30</span>)) </span>
<span id="cb170-6"><a href="statsfreq.html#cb170-6"></a>  </span>
<span id="cb170-7"><a href="statsfreq.html#cb170-7"></a>  </span>
<span id="cb170-8"><a href="statsfreq.html#cb170-8"></a><span class="co"># In the code above I&#39;ve gathered the data into a tidy format </span></span>
<span id="cb170-9"><a href="statsfreq.html#cb170-9"></a></span>
<span id="cb170-10"><a href="statsfreq.html#cb170-10"></a></span>
<span id="cb170-11"><a href="statsfreq.html#cb170-11"></a>ImaginaryScenario1 &lt;-<span class="st"> </span>Sce1 <span class="op">%&gt;%</span></span>
<span id="cb170-12"><a href="statsfreq.html#cb170-12"></a><span class="st">  </span><span class="kw">ggplot</span> (<span class="kw">aes</span> (<span class="dt">x =</span> Count, <span class="dt">y =</span> DustYield)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb170-13"><a href="statsfreq.html#cb170-13"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">shape =</span> Condition, <span class="dt">colour =</span> Condition)) <span class="op">+</span></span>
<span id="cb170-14"><a href="statsfreq.html#cb170-14"></a><span class="st">  </span><span class="kw">labs</span> (<span class="dt">y =</span> <span class="st">&quot;Dust Yield (Kg)&quot;</span>, <span class="dt">x =</span> <span class="st">&quot;Unicorn ID Number&quot;</span>) <span class="op">+</span></span>
<span id="cb170-15"><a href="statsfreq.html#cb170-15"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">200</span>)) <span class="op">+</span></span>
<span id="cb170-16"><a href="statsfreq.html#cb170-16"></a><span class="st">  </span><span class="kw">theme_classic</span> ()</span>
<span id="cb170-17"><a href="statsfreq.html#cb170-17"></a>  </span>
<span id="cb170-18"><a href="statsfreq.html#cb170-18"></a><span class="co"># I have also made this chart an object because we&#39;re going to update it</span></span>
<span id="cb170-19"><a href="statsfreq.html#cb170-19"></a><span class="co"># It&#39;s quicker to do this as an object</span></span>
<span id="cb170-20"><a href="statsfreq.html#cb170-20"></a><span class="co"># You can compare how we update this chart with how we update the ones above.</span></span>
<span id="cb170-21"><a href="statsfreq.html#cb170-21"></a></span>
<span id="cb170-22"><a href="statsfreq.html#cb170-22"></a>ImaginaryScenario1</span></code></pre></div>
<p><img src="ratrdsvs_files/figure-html/unnamed-chunk-235-1.png" width="672" /></p>
<p>We could fit the mean of the dataset on this:</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="statsfreq.html#cb171-1"></a>ImaginaryScenario1 <span class="op">+</span></span>
<span id="cb171-2"><a href="statsfreq.html#cb171-2"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="kw">mean</span>(Sce1<span class="op">$</span>DustYield))</span></code></pre></div>
<p><img src="ratrdsvs_files/figure-html/unnamed-chunk-236-1.png" width="672" /></p>
<p>Let’s compare the overall mean with the group means, and see which one is the best guess for any given data point. Remember - if the condition is explaining a lot of the variation around our response, we’ll see less deviation from each group mean than the overall mean.</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="statsfreq.html#cb172-1"></a>Sce1 <span class="op">%&gt;%</span></span>
<span id="cb172-2"><a href="statsfreq.html#cb172-2"></a><span class="st">  </span><span class="kw">group_by</span>(Condition) <span class="op">%&gt;%</span></span>
<span id="cb172-3"><a href="statsfreq.html#cb172-3"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean =</span> <span class="kw">mean</span> (DustYield))</span></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   Condition   mean
##   &lt;chr&gt;      &lt;dbl&gt;
## 1 Condition1 100. 
## 2 Condition2 121  
## 3 Condition3  84.2</code></pre>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="statsfreq.html#cb174-1"></a>ImaginaryScenario1 <span class="op">+</span></span>
<span id="cb174-2"><a href="statsfreq.html#cb174-2"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="kw">mean</span>(Sce1<span class="op">$</span>DustYield)) <span class="op">+</span></span>
<span id="cb174-3"><a href="statsfreq.html#cb174-3"></a><span class="st">  </span><span class="kw">geom_segment</span>(<span class="kw">aes</span>(<span class="dt">x =</span><span class="dv">1</span>, <span class="dt">y =</span> <span class="fl">100.1</span>, <span class="dt">xend =</span><span class="dv">10</span>, <span class="dt">yend =</span> <span class="fl">100.1</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>)) <span class="op">+</span></span>
<span id="cb174-4"><a href="statsfreq.html#cb174-4"></a><span class="st">  </span><span class="kw">geom_segment</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="dv">11</span>, <span class="dt">y =</span> <span class="fl">121.0</span>, <span class="dt">xend =</span> <span class="dv">20</span>, <span class="dt">yend =</span> <span class="fl">121.0</span>, <span class="dt">color =</span> <span class="st">&quot;green&quot;</span>)) <span class="op">+</span></span>
<span id="cb174-5"><a href="statsfreq.html#cb174-5"></a><span class="st">  </span><span class="kw">geom_segment</span> (<span class="kw">aes</span>(<span class="dt">x =</span> <span class="dv">21</span>, <span class="dt">y =</span> <span class="fl">84.2</span>, <span class="dt">xend =</span> <span class="dv">30</span>, <span class="dt">yend =</span> <span class="fl">84.2</span>, <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>)) <span class="op">+</span></span>
<span id="cb174-6"><a href="statsfreq.html#cb174-6"></a><span class="st">  </span><span class="kw">theme</span> (<span class="dt">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<p><img src="ratrdsvs_files/figure-html/unnamed-chunk-237-1.png" width="672" /></p>
<p>In this case, the individual group means are a better description of the group than the overall population mean. Any statistics we were to apply would simply put a number to what we see on this chart.</p>
<p>So let’s look at a second scenario:</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="statsfreq.html#cb175-1"></a>Sce2&lt;-<span class="kw">tibble</span> (<span class="dt">Condition1 =</span> <span class="kw">c</span>(<span class="dv">84</span>,<span class="dv">86</span>,<span class="dv">123</span>,<span class="dv">95</span>,<span class="dv">87</span>,<span class="dv">110</span>,<span class="dv">99</span>,<span class="dv">95</span>,<span class="dv">121</span>,<span class="dv">121</span>),</span>
<span id="cb175-2"><a href="statsfreq.html#cb175-2"></a>              <span class="dt">Condition2 =</span> <span class="kw">c</span>(<span class="dv">83</span>,<span class="dv">115</span>,<span class="dv">85</span>,<span class="dv">85</span>, <span class="dv">110</span>,<span class="dv">105</span>,<span class="dv">84</span>,<span class="dv">115</span>,<span class="dv">101</span>,<span class="dv">100</span>),</span>
<span id="cb175-3"><a href="statsfreq.html#cb175-3"></a>              <span class="dt">Condition3 =</span> <span class="kw">c</span>(<span class="dv">84</span>,<span class="dv">122</span>,<span class="dv">80</span>,<span class="dv">80</span>,<span class="dv">101</span>,<span class="dv">83</span>,<span class="dv">83</span>,<span class="dv">99</span>, <span class="dv">120</span>,<span class="dv">120</span>)) <span class="op">%&gt;%</span></span>
<span id="cb175-4"><a href="statsfreq.html#cb175-4"></a><span class="st">  </span><span class="kw">pivot_longer</span> (<span class="dt">cols =</span> <span class="kw">c</span>(Condition1<span class="op">:</span>Condition3), <span class="dt">names_to =</span> <span class="st">&quot;Condition&quot;</span>, <span class="dt">values_to =</span> <span class="st">&quot;DustYield&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb175-5"><a href="statsfreq.html#cb175-5"></a><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">Count =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">30</span>)) </span>
<span id="cb175-6"><a href="statsfreq.html#cb175-6"></a>  </span>
<span id="cb175-7"><a href="statsfreq.html#cb175-7"></a>Sce2 <span class="op">%&gt;%</span></span>
<span id="cb175-8"><a href="statsfreq.html#cb175-8"></a><span class="st">  </span><span class="kw">group_by</span>(Condition) <span class="op">%&gt;%</span></span>
<span id="cb175-9"><a href="statsfreq.html#cb175-9"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean =</span> <span class="kw">mean</span> (DustYield))</span></code></pre></div>
<pre><code>## # A tibble: 3 x 2
##   Condition   mean
##   &lt;chr&gt;      &lt;dbl&gt;
## 1 Condition1 102. 
## 2 Condition2  98.3
## 3 Condition3  97.2</code></pre>
<p>Now we chart it, and add our segment lines for each group’s mean:</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="statsfreq.html#cb177-1"></a>Sce2 <span class="op">%&gt;%</span></span>
<span id="cb177-2"><a href="statsfreq.html#cb177-2"></a><span class="st">  </span><span class="kw">ggplot</span> (<span class="kw">aes</span> (<span class="dt">x =</span> Count, <span class="dt">y =</span> DustYield)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb177-3"><a href="statsfreq.html#cb177-3"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">shape =</span> Condition, <span class="dt">colour =</span> Condition)) <span class="op">+</span></span>
<span id="cb177-4"><a href="statsfreq.html#cb177-4"></a><span class="st">  </span><span class="kw">labs</span> (<span class="dt">y =</span> <span class="st">&quot;Dust Yield (Kg)&quot;</span>, <span class="dt">x =</span> <span class="st">&quot;Unicorn ID Number&quot;</span>) <span class="op">+</span></span>
<span id="cb177-5"><a href="statsfreq.html#cb177-5"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">200</span>)) <span class="op">+</span></span>
<span id="cb177-6"><a href="statsfreq.html#cb177-6"></a><span class="st">  </span><span class="kw">theme_classic</span> () <span class="op">+</span></span>
<span id="cb177-7"><a href="statsfreq.html#cb177-7"></a><span class="st">  </span><span class="kw">geom_hline</span>(<span class="dt">yintercept =</span> <span class="kw">mean</span>(Sce2<span class="op">$</span>DustYield)) <span class="op">+</span></span>
<span id="cb177-8"><a href="statsfreq.html#cb177-8"></a><span class="st">  </span><span class="kw">geom_segment</span>(<span class="kw">aes</span>(<span class="dt">x =</span><span class="dv">1</span>, <span class="dt">y =</span> <span class="fl">102.1</span>, <span class="dt">xend =</span><span class="dv">10</span>, <span class="dt">yend =</span> <span class="fl">102.1</span>, <span class="dt">color =</span> <span class="st">&quot;red&quot;</span>)) <span class="op">+</span></span>
<span id="cb177-9"><a href="statsfreq.html#cb177-9"></a><span class="st">  </span><span class="kw">geom_segment</span>(<span class="kw">aes</span>(<span class="dt">x =</span> <span class="dv">11</span>, <span class="dt">y =</span> <span class="fl">98.3</span>, <span class="dt">xend =</span> <span class="dv">20</span>, <span class="dt">yend =</span> <span class="fl">98.3</span>, <span class="dt">color =</span> <span class="st">&quot;green&quot;</span>)) <span class="op">+</span></span>
<span id="cb177-10"><a href="statsfreq.html#cb177-10"></a><span class="st">  </span><span class="kw">geom_segment</span> (<span class="kw">aes</span>(<span class="dt">x =</span> <span class="dv">21</span>, <span class="dt">y =</span> <span class="fl">97.2</span>, <span class="dt">xend =</span> <span class="dv">30</span>, <span class="dt">yend =</span> <span class="fl">97.2</span>, <span class="dt">color =</span> <span class="st">&quot;blue&quot;</span>)) <span class="op">+</span></span>
<span id="cb177-11"><a href="statsfreq.html#cb177-11"></a><span class="st">  </span><span class="kw">theme</span> (<span class="dt">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<p><img src="ratrdsvs_files/figure-html/unnamed-chunk-239-1.png" width="672" style="display: block; margin: auto;" /></p>
<p>In this second scenaro, the population mean is not very different from the means of each of the three conditions. In fact, it’s hard to see some of those means on the chart! We haven’t successfully partitioned off any of the dataset’s varaiance by looking at each of the condition means.</p>
<p>In this second scenario, the explanatory variable is not explaining very much of the response variable at all.</p>
</div>
</div>
<div id="our-scenario" class="section level4">
<h4><span class="header-section-number">10.1.2.6</span> Our Scenario</h4>
<p>If we plot our unicorn data in the same format:</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="statsfreq.html#cb178-1"></a>RadioTidy <span class="op">%&gt;%</span></span>
<span id="cb178-2"><a href="statsfreq.html#cb178-2"></a><span class="st">  </span><span class="kw">mutate</span>(<span class="dt">count =</span> <span class="kw">c</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">30</span>)) <span class="op">%&gt;%</span></span>
<span id="cb178-3"><a href="statsfreq.html#cb178-3"></a><span class="st">  </span><span class="kw">ggplot</span> (<span class="kw">aes</span> (<span class="dt">x =</span> count, <span class="dt">y =</span> DustYield)) <span class="op">+</span><span class="st"> </span></span>
<span id="cb178-4"><a href="statsfreq.html#cb178-4"></a><span class="st">  </span><span class="kw">geom_point</span>(<span class="kw">aes</span>(<span class="dt">shape =</span> Radio, <span class="dt">colour =</span> Radio)) <span class="op">+</span></span>
<span id="cb178-5"><a href="statsfreq.html#cb178-5"></a><span class="st">  </span><span class="kw">labs</span> (<span class="dt">title =</span> <span class="st">&quot;Magic Dust Yield(kg)&quot;</span>, <span class="dt">y =</span> <span class="st">&quot;Dust Yield (Kg)&quot;</span>, <span class="dt">x =</span> <span class="st">&quot;Unicorn ID Number&quot;</span>) <span class="op">+</span></span>
<span id="cb178-6"><a href="statsfreq.html#cb178-6"></a><span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">200</span>)) <span class="op">+</span></span>
<span id="cb178-7"><a href="statsfreq.html#cb178-7"></a><span class="st">  </span><span class="kw">theme_classic</span> ()</span></code></pre></div>
<p><img src="ratrdsvs_files/figure-html/unnamed-chunk-240-1.png" width="672" /></p>
<div id="going-back-to-sums-of-squares" class="section level5">
<h5><span class="header-section-number">10.1.2.6.1</span> Going Back to Sums of Squares</h5>
<p>In our two imaginary scenarios above we were (roughly) partitioning variances by drawing lines on our charts - much like we could draw a line of best fit on the perfect data chart earlier.</p>
<p>When we run a model, we want to describe that chart mathematically.</p>
<p>When we calculated variance earlier, we calculated the variance in the condition mean mean (e.g. the variance for No Radio data). We can call this the <strong>Error Sum of Squares (SSE)</strong> which is the sum of the squares of the deviations of the data around the means of each group.</p>
<p>We could also calculate …</p>
<ul>
<li><strong>Total Sums of Squares (SSY)</strong>, the sums of squares of the deviations of the data around the population mean.</li>
<li><strong>Condition Sums of Squares (SSF)</strong>, the sums of squares of the deviations of each condition mean from the population mean.</li>
</ul>
<p>But why would we use any sums of squares when we already establishd that variance was a better measure?</p>
<p>Let’s rearrange our data so we have for each ‘row’ the condition mean and total mean. We’re going to call this dataset <code>MFY</code> for short because:</p>
<ul>
<li><p>M is the global mean</p></li>
<li><p>F is the condition mean</p></li>
<li><p>Y is the ‘response variable’</p></li>
</ul>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="statsfreq.html#cb179-1"></a>MFY &lt;-<span class="st"> </span>RadioTidy <span class="op">%&gt;%</span></span>
<span id="cb179-2"><a href="statsfreq.html#cb179-2"></a><span class="st">  </span><span class="kw">mutate</span> (<span class="st">&quot;Y&quot;</span> =<span class="st"> </span>DustYield) <span class="op">%&gt;%</span></span>
<span id="cb179-3"><a href="statsfreq.html#cb179-3"></a><span class="st">  </span><span class="kw">mutate</span> (<span class="st">&quot;M&quot;</span> =<span class="st"> </span><span class="kw">mean</span>(Y)) <span class="op">%&gt;%</span></span>
<span id="cb179-4"><a href="statsfreq.html#cb179-4"></a><span class="st">  </span><span class="co"># If we now ask R to group the data, it will calculate the mean per group:</span></span>
<span id="cb179-5"><a href="statsfreq.html#cb179-5"></a><span class="st">  </span><span class="kw">group_by</span>(Radio) <span class="op">%&gt;%</span></span>
<span id="cb179-6"><a href="statsfreq.html#cb179-6"></a><span class="st">  </span><span class="kw">mutate</span> (<span class="st">&quot;F&quot;</span> =<span class="st"> </span><span class="kw">mean</span>(Y)) <span class="op">%&gt;%</span></span>
<span id="cb179-7"><a href="statsfreq.html#cb179-7"></a><span class="st">  </span><span class="co"># Remember to ungroup after!</span></span>
<span id="cb179-8"><a href="statsfreq.html#cb179-8"></a><span class="st">  </span><span class="kw">ungroup</span>() </span>
<span id="cb179-9"><a href="statsfreq.html#cb179-9"></a><span class="co">#  I suggest you View(MFY)</span></span></code></pre></div>
<p>We can also calculate:</p>
<ul>
<li><p>MY (The data - Dataset mean)</p></li>
<li><p>MF (The condition mean - dataset mean)</p></li>
<li><p>FY (The data - condition mean)</p></li>
</ul>
<div class="sourceCode" id="cb180"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb180-1"><a href="statsfreq.html#cb180-1"></a>MFY &lt;-<span class="st"> </span>MFY <span class="op">%&gt;%</span></span>
<span id="cb180-2"><a href="statsfreq.html#cb180-2"></a><span class="st"> </span><span class="kw">mutate</span> (<span class="dt">MY =</span> (Y<span class="op">-</span>M),</span>
<span id="cb180-3"><a href="statsfreq.html#cb180-3"></a>         <span class="dt">MF =</span> (F<span class="op">-</span>M),</span>
<span id="cb180-4"><a href="statsfreq.html#cb180-4"></a>         <span class="dt">FY =</span> (Y <span class="op">-</span><span class="st"> </span>F))</span></code></pre></div>
<p>We’ve calculated a lot of deviations here - but we said we always wanted to square those deviations, so:</p>
<div class="sourceCode" id="cb181"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb181-1"><a href="statsfreq.html#cb181-1"></a>MFY &lt;-<span class="st"> </span>MFY <span class="op">%&gt;%</span></span>
<span id="cb181-2"><a href="statsfreq.html#cb181-2"></a><span class="st">  </span><span class="kw">mutate</span> (<span class="dt">MY2 =</span> (MY<span class="op">*</span>MY),</span>
<span id="cb181-3"><a href="statsfreq.html#cb181-3"></a>          <span class="dt">MF2 =</span> (MF<span class="op">*</span>MF),</span>
<span id="cb181-4"><a href="statsfreq.html#cb181-4"></a>          <span class="dt">FY2 =</span> (FY<span class="op">*</span>FY))</span></code></pre></div>
<p>MY2, MF2 &amp; FY2 are the squares of the deviations, but we need a sum of squares for each one.</p>
<div class="sourceCode" id="cb182"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb182-1"><a href="statsfreq.html#cb182-1"></a>MFY <span class="op">%&gt;%</span></span>
<span id="cb182-2"><a href="statsfreq.html#cb182-2"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">SumSquareMY =</span> <span class="kw">sum</span>(MY2),</span>
<span id="cb182-3"><a href="statsfreq.html#cb182-3"></a>            <span class="dt">SumSquareMF =</span> <span class="kw">sum</span>(MF2),</span>
<span id="cb182-4"><a href="statsfreq.html#cb182-4"></a>            <span class="dt">SumSquareFY =</span> <span class="kw">sum</span>(FY2))</span></code></pre></div>
<pre><code>## # A tibble: 1 x 3
##   SumSquareMY SumSquareMF SumSquareFY
##         &lt;dbl&gt;       &lt;dbl&gt;       &lt;dbl&gt;
## 1      12053.       6301.       5752.</code></pre>
<p>But we also have one more bit of information we need to consider - what we call <strong>degrees of freedom</strong>. Let’s say we want to put those sum squares into a nice table. We could also add in a row talking about the degrees of freedom.</p>
<p>There are degrees of freedom for:</p>
<ul>
<li><p><strong>M</strong> - which is 1. There is only 1 bit of information in the whole group mean</p></li>
<li><p><strong>F</strong> - which is 3. There are only 3 means in the conditions.</p></li>
<li><p><strong>Y</strong> - which is 30. We have 30 data points to observe.</p></li>
</ul>
<p>If you were to calculate the degrees of freedom (dof) for MY, MF and FY - you can run the same calculation:</p>
<ul>
<li><p><strong>MY</strong> (Ydof - Mdof = 30 - 1 = 29)</p></li>
<li><p><strong>MF</strong> (Fdof - Mdof = 3 - 1 = 2)</p></li>
<li><p><strong>FY</strong> (Ydof - Fdof = 30 - 3 = 27)</p></li>
</ul>
<p>We can calculate something called <strong>mean squares</strong> which is:
<code>Mean Squares = Sum of Squares / Degrees of Freedom</code></p>
<p>So:</p>
<ul>
<li><p><strong>MS-MY</strong> = (12053.2/ 29) = 415.6276</p></li>
<li><p><strong>MS-MF</strong> = (6301.4/2) = 3150.7</p></li>
<li><p><strong>MS-FY</strong> = (5751.8/27) = 213.0296</p></li>
</ul>
<p>And this is pretty much all we can do with the data.</p>
<div class="sourceCode" id="cb184"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb184-1"><a href="statsfreq.html#cb184-1"></a><span class="co"># I&#39;m using the package &#39;knitr&#39; to display this. </span></span>
<span id="cb184-2"><a href="statsfreq.html#cb184-2"></a></span>
<span id="cb184-3"><a href="statsfreq.html#cb184-3"></a>knitr<span class="op">::</span><span class="kw">kable</span>(MFY <span class="op">%&gt;%</span></span>
<span id="cb184-4"><a href="statsfreq.html#cb184-4"></a><span class="st">        </span><span class="kw">summarise</span>(<span class="dt">SumSquareMY =</span> <span class="kw">sum</span>(MY2),</span>
<span id="cb184-5"><a href="statsfreq.html#cb184-5"></a>                  <span class="dt">SumSquareMF =</span> <span class="kw">sum</span>(MF2),</span>
<span id="cb184-6"><a href="statsfreq.html#cb184-6"></a>                  <span class="dt">SumSquareFY =</span> <span class="kw">sum</span>(FY2),</span>
<span id="cb184-7"><a href="statsfreq.html#cb184-7"></a>                  <span class="dt">MeanSquareMY =</span> <span class="kw">sum</span>(MY2)<span class="op">/</span><span class="dv">29</span>,</span>
<span id="cb184-8"><a href="statsfreq.html#cb184-8"></a>                  <span class="dt">MeanSquareMF =</span> <span class="kw">sum</span>(MF2)<span class="op">/</span><span class="dv">2</span>,</span>
<span id="cb184-9"><a href="statsfreq.html#cb184-9"></a>                  <span class="dt">MeanSquareFY =</span> <span class="kw">sum</span>(FY2)<span class="op">/</span><span class="dv">27</span>))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">SumSquareMY</th>
<th align="right">SumSquareMF</th>
<th align="right">SumSquareFY</th>
<th align="right">MeanSquareMY</th>
<th align="right">MeanSquareMF</th>
<th align="right">MeanSquareFY</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">12053.2</td>
<td align="right">6301.4</td>
<td align="right">5751.8</td>
<td align="right">415.6276</td>
<td align="right">3150.7</td>
<td align="right">213.0296</td>
</tr>
</tbody>
</table>
<p>Earlier we said variance was important because it took into account the size of the dataset.</p>
<p>Mean Squares are very similar to the variance calculation, because they’re a measure of deviation in relation to the size of the dataset.</p>
</div>
</div>
<div id="the-importance-of-mean-squares" class="section level4">
<h4><span class="header-section-number">10.1.2.7</span> The Importance of Mean Squares</h4>
<p>If the condition (radio) has no effect on the data, then the variation we would see between the farms would be similar to the variation we saw within any given farm. It would be like Scenario 2, where the mean of the farm was no more use to us than the mean of the overall population.</p>
<p>If that were the case: the <code>Condition Mean Square (FMS)  / Error Mean Square (EMS) = 1</code></p>
<p>Let’s look again at that last table.</p>
<div class="sourceCode" id="cb185"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb185-1"><a href="statsfreq.html#cb185-1"></a>knitr<span class="op">::</span><span class="kw">kable</span>(MFY <span class="op">%&gt;%</span></span>
<span id="cb185-2"><a href="statsfreq.html#cb185-2"></a><span class="st">        </span><span class="kw">summarise</span>(<span class="dt">SumSquareMY =</span> <span class="kw">sum</span>(MY2),</span>
<span id="cb185-3"><a href="statsfreq.html#cb185-3"></a>                  <span class="dt">SumSquareMF =</span> <span class="kw">sum</span>(MF2),</span>
<span id="cb185-4"><a href="statsfreq.html#cb185-4"></a>                  <span class="dt">SumSquareFY =</span> <span class="kw">sum</span>(FY2),</span>
<span id="cb185-5"><a href="statsfreq.html#cb185-5"></a>                  <span class="dt">MeanSquareMY =</span> <span class="kw">sum</span>(MY2)<span class="op">/</span><span class="dv">29</span>,</span>
<span id="cb185-6"><a href="statsfreq.html#cb185-6"></a>                  <span class="dt">MeanSquareMF =</span> <span class="kw">sum</span>(MF2)<span class="op">/</span><span class="dv">2</span>,</span>
<span id="cb185-7"><a href="statsfreq.html#cb185-7"></a>                  <span class="dt">MeanSquareFY =</span> <span class="kw">sum</span>(FY2)<span class="op">/</span><span class="dv">27</span>))</span></code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">SumSquareMY</th>
<th align="right">SumSquareMF</th>
<th align="right">SumSquareFY</th>
<th align="right">MeanSquareMY</th>
<th align="right">MeanSquareMF</th>
<th align="right">MeanSquareFY</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">12053.2</td>
<td align="right">6301.4</td>
<td align="right">5751.8</td>
<td align="right">415.6276</td>
<td align="right">3150.7</td>
<td align="right">213.0296</td>
</tr>
</tbody>
</table>
<p>And now we will take the Condition Mean Square and Error Mean Squares from that table:</p>
<ul>
<li><p>FMS = 3150.7</p></li>
<li><p>ENS = 213.0296</p></li>
</ul>
<p>And we’ll call this the F Ratio.</p>
<div class="sourceCode" id="cb186"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb186-1"><a href="statsfreq.html#cb186-1"></a><span class="fl">3150.7</span><span class="op">/</span><span class="fl">213.0296</span></span></code></pre></div>
<pre><code>## [1] 14.78996</code></pre>
</div>
<div id="f-ratios-and-f-distributions" class="section level4">
<h4><span class="header-section-number">10.1.2.8</span> F Ratios and F Distributions</h4>
<p>Because the mean squares are standardised by the size of the dataset, we can mathematically calculate the range and likelihood of any F-Ratio. This is called the F Distribution.</p>
<p>You can <a href="http://www.socr.ucla.edu/Applets.dir/F_Table.html">look up</a> F distributions for an alpha level of 0.05. <a href="http://www.socr.ucla.edu/Applets.dir/F_Table.html#FTable0.05">Click here to go directly there</a>. We are interested in the ratio between 2 and 27 degrees of freedom, which gives us a critical F ratio of <strong>3.3541</strong>, which our F Ratio (14.79) is much bigger than.</p>
<p>In fact, if we were to plot a curve of the F Distribution between 2 and 27 degrees of freedom, less than 0.001% of the total area would be more than 14.79.</p>
</div>
<div id="in-conclusion-.-.-." class="section level4">
<h4><span class="header-section-number">10.1.2.9</span> In Conclusion . . .</h4>
<blockquote>
<p>The probability of getting an F-Ratio as large as 14.8 (or larger), if the null hypothes (x has no effect on y) is true, is less than 0.001</p>
</blockquote>
<blockquote>
<p>Or: F (between 2 and 27 degrees of freedom) = 14.79, and P &lt; 0.001</p>
</blockquote>
<p><strong>CONGRATULATIONS!</strong></p>
<p>You just ran an ANOVA completely by hand.</p>
</div>
<div id="prove-it" class="section level4">
<h4><span class="header-section-number">10.1.2.10</span> Prove It</h4>
<p>Of course, we don’t run ANOVAs by hand. We don’t use all these steps to run an ANOVA. Instead we go back to the RadioTidy data, which if you <code>View(RadioTidy)</code>, you will note doesn’t have any of our squares or sum squares or mean squares calculated.</p>
<p>And we ask R to run an ANOVA:</p>
<div class="sourceCode" id="cb188"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb188-1"><a href="statsfreq.html#cb188-1"></a>ANOVA &lt;-<span class="st"> </span><span class="kw">aov</span>(DustYield <span class="op">~</span><span class="st"> </span>Radio, <span class="dt">data =</span> RadioTidy)</span>
<span id="cb188-2"><a href="statsfreq.html#cb188-2"></a><span class="kw">summary</span>(ANOVA)</span></code></pre></div>
<pre><code>##             Df Sum Sq Mean Sq F value  Pr(&gt;F)    
## Radio        2   6301    3151   14.79 4.6e-05 ***
## Residuals   27   5752     213                    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>And that command <code>summary(ANOVA)</code> gives us a table exactly like the one we calculated by ourselves.</p>
<p>When we say that radio has a significant effect on the dust yield of unicorns in an ANOVA (F<sup>2,27</sup>=14.79, P&lt;0.001) - you now know exactly what those numbers refer to.</p>
<p>And now that you’ve run it by yourself, what would you recommend to the unicorn farmers of Scotland?</p>

</div>
</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="statsbasic.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="choosestats.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"collapse": "subsection"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
